// The recipe catalog, seeded into the `recipes` collection. Ingredient names
// are kept generic ("Spinach", "Eggs", "Cheddar cheese") so they match the
// shelf items a user is likely to have, rather than brand- or cut-specific
// names. Matching against the shelf is handled in routes/recipes.js.
//
// Tags drive the filter chips on the recipe page, so keep them consistent
// across recipes (reuse an existing tag before inventing a new one).

export const recipeCatalog = [
  {
    id: "spinach-cheddar-omelet",
    name: "Spinach Cheddar Omelet",
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 1,
    difficulty: "Easy",
    tags: ["Breakfast", "Vegetarian", "High-protein", "Quick"],
    ingredients: [
      "Eggs",
      "Spinach",
      "Cheddar cheese",
      "Butter",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Beat three eggs with a pinch of salt and pepper.",
      "Melt a little butter over medium heat and wilt the spinach for a minute.",
      "Pour in the eggs, let them set around the edges, then scatter cheddar over one half.",
      "Fold the omelet over the cheese and slide it onto a plate.",
    ],
    mealPrepFriendly: true,
    notes:
      "Pull it off the heat while the center still looks a touch wet — it keeps cooking on the plate.",
  },
  {
    id: "ham-cheese-breakfast-casserole",
    name: "Ham and Cheese Breakfast Casserole",
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    servings: 6,
    difficulty: "Medium",
    tags: ["Breakfast", "High-protein", "Meal prep", "Make-ahead"],
    ingredients: [
      "Ham",
      "Eggs",
      "Cheddar cheese",
      "Milk",
      "Bread",
      "Green onion",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Heat the oven to 375°F and butter a baking dish.",
      "Tear the bread into chunks and spread them across the dish with the diced ham.",
      "Whisk the eggs with milk, salt, and pepper, then pour it over the bread.",
      "Top with cheddar and sliced green onion and bake 35–40 minutes until the center is set.",
    ],
    mealPrepFriendly: true,
    notes:
      "Assemble it the night before and bake straight from the fridge — add five minutes.",
  },
  {
    id: "creamy-spinach-pasta",
    name: "Creamy Spinach Pasta",
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 3,
    difficulty: "Easy",
    tags: ["Dinner", "Vegetarian", "Pasta", "Quick"],
    ingredients: [
      "Spaghetti",
      "Spinach",
      "Milk",
      "Cheddar cheese",
      "Garlic",
      "Olive oil",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Boil the spaghetti until just shy of al dente, saving a mug of the pasta water.",
      "Soften the garlic in olive oil, then add the spinach and let it collapse.",
      "Stir in milk and cheddar until you have a loose sauce, loosening with pasta water as needed.",
      "Toss the drained pasta through the sauce and season to taste.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "ham-spinach-frittata",
    name: "Ham and Spinach Frittata",
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 4,
    difficulty: "Medium",
    tags: ["Breakfast", "High-protein", "Meal prep"],
    ingredients: [
      "Ham",
      "Spinach",
      "Eggs",
      "Cheddar cheese",
      "Milk",
      "Onion",
      "Olive oil",
    ],
    instructions: [
      "Heat the oven to 375°F.",
      "Cook the onion and ham in an oven-safe skillet until the onion turns soft.",
      "Add the spinach, then pour over the eggs beaten with a splash of milk.",
      "Scatter cheddar on top and bake 18–20 minutes until puffed and golden.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "loaded-scramble",
    name: "Loaded Pantry Scramble",
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: "Easy",
    tags: ["Breakfast", "High-protein", "Quick"],
    ingredients: ["Eggs", "Milk", "Ham", "Spinach", "Cheddar cheese", "Bread"],
    instructions: [
      "Whisk the eggs with a splash of milk.",
      "Cook the ham and spinach in a skillet for a minute, then pour in the eggs.",
      "Stir gently until just set, fold in the cheddar, and serve with toast.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "banana-oat-pancakes",
    name: "Banana Oat Pancakes",
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: "Easy",
    tags: ["Breakfast", "Vegetarian", "Kid-friendly"],
    ingredients: ["Bananas", "Eggs", "Oats", "Milk", "Butter"],
    instructions: [
      "Mash two ripe bananas and beat in the eggs.",
      "Stir in oats and enough milk to make a thick, spoonable batter, then rest it five minutes.",
      "Cook spoonfuls in a buttered pan over medium-low until bubbles form, then flip.",
    ],
    mealPrepFriendly: true,
    notes:
      "The spottier the bananas, the sweeter the pancakes — a good use for ones past their best.",
  },
  {
    id: "banana-yogurt-smoothie",
    name: "Banana Berry Yogurt Smoothie",
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 2,
    difficulty: "Easy",
    tags: ["Breakfast", "Vegetarian", "No-cook", "Quick"],
    ingredients: ["Bananas", "Greek yogurt", "Milk", "Frozen blueberries"],
    instructions: [
      "Drop the bananas, yogurt, and a handful of frozen blueberries into a blender.",
      "Pour in milk until it reaches the blade and blend until smooth.",
      "Add more milk for a thinner drink, or more frozen fruit to thicken.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "garlic-butter-salmon",
    name: "Garlic Butter Salmon",
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: "Medium",
    tags: ["Dinner", "High-protein", "Seafood"],
    ingredients: [
      "Salmon",
      "Butter",
      "Garlic",
      "Lemon",
      "Spinach",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Pat the salmon dry and season both sides with salt and pepper.",
      "Sear it skin-side down in a little butter until the skin crisps, then flip.",
      "Add more butter, the minced garlic, and a squeeze of lemon, spooning it over the fish.",
      "Wilt the spinach in the same pan and serve it underneath the fillets.",
    ],
    mealPrepFriendly: false,
    notes:
      "Salmon is done when it flakes but still looks glossy in the middle.",
  },
  {
    id: "sheet-pan-chicken-veg",
    name: "Sheet-Pan Chicken and Vegetables",
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    tags: ["Dinner", "High-protein", "Meal prep", "One-pan"],
    ingredients: [
      "Chicken breast",
      "Carrots",
      "Bell peppers",
      "Onion",
      "Olive oil",
      "Garlic",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Heat the oven to 425°F.",
      "Cut the chicken and vegetables into similar-sized pieces and spread them on a sheet pan.",
      "Toss with olive oil, minced garlic, salt, and pepper.",
      "Roast 25–30 minutes, stirring once, until the chicken is cooked through and the edges char.",
    ],
    mealPrepFriendly: true,
    notes: "Portion the leftovers over rice for three days of lunches.",
  },
  {
    id: "chicken-fried-rice",
    name: "Chicken Fried Rice",
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Medium",
    tags: ["Dinner", "High-protein", "One-pan", "Quick"],
    ingredients: [
      "Rice",
      "Chicken breast",
      "Eggs",
      "Frozen peas",
      "Carrots",
      "Garlic",
      "Soy sauce",
      "Green onion",
    ],
    instructions: [
      "Use day-old cold rice if you have it — fresh rice turns gummy.",
      "Scramble the eggs in a hot, oiled pan and set them aside.",
      "Stir-fry the diced chicken, carrots, garlic, and peas until the chicken is cooked.",
      "Add the rice and soy sauce, fold the egg back in, and finish with green onion.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "black-bean-quesadilla",
    name: "Black Bean Quesadillas",
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: "Easy",
    tags: ["Lunch", "Vegetarian", "Quick", "Kid-friendly"],
    ingredients: [
      "Tortillas",
      "Black beans",
      "Cheddar cheese",
      "Bell peppers",
      "Onion",
    ],
    instructions: [
      "Mash the black beans lightly with a fork and stir in diced peppers and onion.",
      "Spread the mixture over half a tortilla, top with cheddar, and fold it over.",
      "Toast in a dry skillet until golden on both sides and the cheese melts.",
      "Let it rest a minute before cutting so the filling stays put.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "black-bean-soup",
    name: "Smoky Black Bean Soup",
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    tags: ["Dinner", "Vegetarian", "Soup", "Meal prep"],
    ingredients: [
      "Black beans",
      "Onion",
      "Garlic",
      "Carrots",
      "Bell peppers",
      "Olive oil",
      "Salt",
    ],
    instructions: [
      "Soften the onion, carrots, and peppers in olive oil with a pinch of salt.",
      "Stir in the garlic, then add the black beans and enough water to cover.",
      "Simmer 20 minutes, then blend about half the pot for a thick, smoky base.",
      "Loosen with water if it tightens up and adjust the salt before serving.",
    ],
    mealPrepFriendly: true,
    notes:
      "Freezes well — ladle into jars once cool and leave room for expansion.",
  },
  {
    id: "spaghetti-aglio-olio",
    name: "Spaghetti Aglio e Olio",
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: "Easy",
    tags: ["Dinner", "Vegetarian", "Pasta", "Quick"],
    ingredients: ["Spaghetti", "Garlic", "Olive oil", "Salt", "Pepper"],
    instructions: [
      "Boil the spaghetti in well-salted water until al dente.",
      "Meanwhile, gently warm thinly sliced garlic in plenty of olive oil until just golden.",
      "Toss the drained pasta in the garlic oil with a splash of pasta water.",
      "Finish with cracked pepper and serve right away.",
    ],
    mealPrepFriendly: false,
    notes:
      "Keep the heat low under the garlic — once it browns past gold it turns bitter.",
  },
  {
    id: "tomato-basil-pasta",
    name: "Fresh Tomato Pasta",
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    servings: 3,
    difficulty: "Easy",
    tags: ["Dinner", "Vegetarian", "Pasta"],
    ingredients: [
      "Spaghetti",
      "Tomatoes",
      "Garlic",
      "Onion",
      "Olive oil",
      "Salt",
    ],
    instructions: [
      "Cook the onion and garlic slowly in olive oil until sweet and soft.",
      "Add chopped tomatoes and a pinch of salt and simmer until they break down into sauce.",
      "Boil the spaghetti, then toss it through the sauce with a little pasta water.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "veggie-egg-muffins",
    name: "Veggie Egg Muffins",
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 6,
    difficulty: "Easy",
    tags: ["Breakfast", "High-protein", "Meal prep", "Make-ahead"],
    ingredients: [
      "Eggs",
      "Spinach",
      "Bell peppers",
      "Cheddar cheese",
      "Onion",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Heat the oven to 350°F and grease a muffin tin.",
      "Divide the chopped spinach, peppers, and onion between the cups.",
      "Beat the eggs with salt and pepper and pour over the vegetables, then top with cheddar.",
      "Bake 18–20 minutes until set and serve, or keep for grab-and-go breakfasts.",
    ],
    mealPrepFriendly: true,
    notes:
      "They keep four days in the fridge and reheat in about thirty seconds.",
  },
  {
    id: "chicken-noodle-soup",
    name: "Chicken Noodle Soup",
    prepTimeMinutes: 15,
    cookTimeMinutes: 35,
    servings: 4,
    difficulty: "Medium",
    tags: ["Dinner", "High-protein", "Soup", "Meal prep"],
    ingredients: [
      "Chicken breast",
      "Carrots",
      "Onion",
      "Garlic",
      "Spaghetti",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Simmer the chicken in salted water with the onion and garlic until cooked, then lift it out and shred.",
      "Add the sliced carrots to the broth and cook until tender.",
      "Break the spaghetti into the pot and cook until soft.",
      "Return the shredded chicken, season well, and serve hot.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "avocado-egg-toast",
    name: "Avocado Egg Toast",
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 1,
    difficulty: "Easy",
    tags: ["Breakfast", "Vegetarian", "Quick"],
    ingredients: ["Bread", "Avocado", "Eggs", "Lemon", "Salt", "Pepper"],
    instructions: [
      "Toast the bread and fry or poach an egg however you like it.",
      "Mash the avocado with a squeeze of lemon, salt, and pepper.",
      "Spread it on the toast and slide the egg on top.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "salmon-rice-bowl",
    name: "Salmon Rice Bowl",
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    servings: 2,
    difficulty: "Medium",
    tags: ["Dinner", "High-protein", "Seafood", "Meal prep"],
    ingredients: [
      "Salmon",
      "Rice",
      "Carrots",
      "Avocado",
      "Soy sauce",
      "Green onion",
    ],
    instructions: [
      "Cook the rice and keep it warm.",
      "Roast or pan-sear the salmon and break it into large flakes.",
      "Build bowls with rice, salmon, shredded carrot, and sliced avocado.",
      "Drizzle with soy sauce and scatter green onion over the top.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "bagel-breakfast-sandwich",
    name: "Egg and Cheese Bagel",
    prepTimeMinutes: 5,
    cookTimeMinutes: 8,
    servings: 1,
    difficulty: "Easy",
    tags: ["Breakfast", "High-protein", "Quick"],
    ingredients: ["Bagels", "Eggs", "Cheddar cheese", "Butter", "Ham"],
    instructions: [
      "Split and toast the bagel, then butter both halves.",
      "Fry an egg, breaking the yolk if you want it tidy, and warm the ham beside it.",
      "Lay the cheddar over the hot egg so it melts, then build the sandwich.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "carrot-ginger-soup",
    name: "Carrot Soup",
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    tags: ["Lunch", "Vegetarian", "Soup", "Meal prep"],
    ingredients: ["Carrots", "Onion", "Garlic", "Butter", "Milk", "Salt"],
    instructions: [
      "Sweat the onion and garlic in butter until soft.",
      "Add the sliced carrots and enough water to cover, then simmer until very tender.",
      "Blend smooth, stir in a splash of milk, and season with salt.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "stuffed-peppers",
    name: "Black Bean Stuffed Peppers",
    prepTimeMinutes: 20,
    cookTimeMinutes: 35,
    servings: 4,
    difficulty: "Medium",
    tags: ["Dinner", "Vegetarian", "Meal prep"],
    ingredients: [
      "Bell peppers",
      "Rice",
      "Black beans",
      "Cheddar cheese",
      "Onion",
      "Tomatoes",
      "Garlic",
    ],
    instructions: [
      "Heat the oven to 375°F and halve the peppers, removing the seeds.",
      "Cook the onion, garlic, and tomatoes, then stir in cooked rice and black beans.",
      "Pack the filling into the peppers and top with cheddar.",
      "Bake 30–35 minutes until the peppers soften and the cheese browns.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "french-toast",
    name: "Classic French Toast",
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 3,
    difficulty: "Easy",
    tags: ["Breakfast", "Vegetarian", "Kid-friendly"],
    ingredients: ["Bread", "Eggs", "Milk", "Butter", "Bananas"],
    instructions: [
      "Whisk the eggs with milk in a shallow dish.",
      "Soak each slice of bread for a few seconds a side — sturdy or slightly stale bread holds up best.",
      "Cook in butter over medium heat until golden, then top with sliced banana.",
    ],
    mealPrepFriendly: false,
    notes: "A great way to rescue bread that has gone a little dry.",
  },
  {
    id: "greek-yogurt-parfait",
    name: "Yogurt and Fruit Parfait",
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    servings: 1,
    difficulty: "Easy",
    tags: ["Breakfast", "Vegetarian", "No-cook", "Quick"],
    ingredients: ["Greek yogurt", "Bananas", "Frozen blueberries", "Oats"],
    instructions: [
      "Layer yogurt, sliced banana, and thawed blueberries in a glass or jar.",
      "Sprinkle oats between the layers for some crunch.",
      "Build it the night before for an easy breakfast that travels well.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "chicken-quesadilla",
    name: "Chicken Quesadillas",
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 2,
    difficulty: "Easy",
    tags: ["Lunch", "High-protein", "Quick"],
    ingredients: [
      "Tortillas",
      "Chicken breast",
      "Cheddar cheese",
      "Bell peppers",
      "Onion",
    ],
    instructions: [
      "Cook the sliced chicken with the peppers and onion until everything is tender.",
      "Lay the filling and cheddar over half a tortilla and fold it closed.",
      "Crisp both sides in a dry skillet until the cheese melts through.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "veggie-stir-fry",
    name: "Garden Vegetable Stir-Fry",
    prepTimeMinutes: 15,
    cookTimeMinutes: 12,
    servings: 3,
    difficulty: "Easy",
    tags: ["Dinner", "Vegetarian", "One-pan", "Quick"],
    ingredients: [
      "Carrots",
      "Bell peppers",
      "Frozen peas",
      "Onion",
      "Garlic",
      "Soy sauce",
      "Rice",
    ],
    instructions: [
      "Get a wide pan very hot and add a little oil.",
      "Stir-fry the firmer vegetables first — carrots and peppers — then the onion.",
      "Add the peas and garlic for the last minute and splash in soy sauce.",
      "Serve over rice while everything still has some bite.",
    ],
    mealPrepFriendly: true,
  },
  {
    id: "tomato-cheddar-grilled-cheese",
    name: "Tomato Cheddar Grilled Cheese",
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 1,
    difficulty: "Easy",
    tags: ["Lunch", "Vegetarian", "Quick", "Kid-friendly"],
    ingredients: ["Bread", "Cheddar cheese", "Tomatoes", "Butter"],
    instructions: [
      "Butter the outsides of two slices of bread.",
      "Layer cheddar and thin tomato slices between them, butter-side out.",
      "Cook low and slow so the cheese melts before the bread gets too dark.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "egg-drop-soup",
    name: "Quick Egg Drop Soup",
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    servings: 2,
    difficulty: "Easy",
    tags: ["Lunch", "Soup", "Quick", "High-protein"],
    ingredients: ["Eggs", "Green onion", "Garlic", "Soy sauce", "Frozen peas"],
    instructions: [
      "Bring a pot of water to a gentle simmer with the garlic and a little soy sauce.",
      "Beat the eggs, then pour them in a thin stream while stirring so they form ribbons.",
      "Add the peas, warm through, and finish with green onion.",
    ],
    mealPrepFriendly: false,
  },
  {
    id: "baked-potato-bar",
    name: "Loaded Baked Potatoes",
    prepTimeMinutes: 10,
    cookTimeMinutes: 55,
    servings: 4,
    difficulty: "Easy",
    tags: ["Dinner", "Vegetarian", "Make-ahead"],
    ingredients: [
      "Potatoes",
      "Cheddar cheese",
      "Black beans",
      "Green onion",
      "Butter",
      "Greek yogurt",
    ],
    instructions: [
      "Heat the oven to 400°F, prick the potatoes, and bake until tender, about 50 minutes.",
      "Warm the black beans while the potatoes finish.",
      "Split each potato and load it with butter, cheddar, beans, yogurt, and green onion.",
    ],
    mealPrepFriendly: false,
    notes: "A dollop of Greek yogurt stands in nicely for sour cream.",
  },
];
